trigger:
- main

pool:
  name: web-test-pool

steps:
- checkout: self

- script: |
    sudo cp -r $(Build.SourcesDirectory)/* /var/www/html/
    sudo systemctl restart nginx
  displayName: 'Deploy Website'